###
GET http://localhost:8080/tasks
Accept: application/json

###
GET http://localhost:8080/
Accept: application/json

###
POST http://localhost:8080/tasks
Content-Type: application/json

{
    "title": "Tarea 1",
    "description": "Descripcion",
    "taskStatus": "completed",
    "status": 1,
    "userId": 1
}

###
GET http://localhost:8080/tasks/1
Accept: application/json